[2025-04-04 16:55:14,470: INFO: main: Welcome to our custom logging datascience]
[2025-04-04 19:49:01,691: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-04 19:51:03,517: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-04 19:51:23,788: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-04 20:09:19,330: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-04 20:20:43,204: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-04 20:20:43,204: INFO: 1770419919: created directory at: artifacts]
[2025-04-04 20:20:43,204: INFO: common: created dictionary at artifacts/data_ingestion]
[2025-04-04 20:24:42,319: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-04 20:24:42,622: INFO: 1770419919: created directory at: artifacts]
[2025-04-04 20:24:42,622: INFO: common: created dictionary at artifacts/data_ingestion]
[2025-04-04 20:24:43,993: INFO: 535005154: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 65ED:3D0951:9E95C0:E83009:67EFF2B2
Accept-Ranges: bytes
Date: Fri, 04 Apr 2025 14:54:43 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4723-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1743778483.220687,VS0,VE385
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: d2785da187cb6cc87e8c1e6701df9526d87bc3dc
Expires: Fri, 04 Apr 2025 14:59:43 GMT
Source-Age: 0

]
[2025-04-04 20:25:08,025: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-04 20:25:08,025: INFO: 1770419919: created directory at: artifacts]
[2025-04-04 20:25:08,025: INFO: common: created dictionary at artifacts/data_ingestion]
[2025-04-04 20:25:08,038: INFO: 535005154: File already exists]
[2025-04-09 03:07:38,140: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<<<< 

x==========x]
[2025-04-09 03:07:38,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 03:07:38,164: INFO: common: created directory at: artifacts]
[2025-04-09 03:07:38,164: INFO: common: created directory at: artifacts/data_ingestion]
[2025-04-09 03:07:39,460: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 0E70:275D06:1547C3:15FDE7:67F59722
Accept-Ranges: bytes
Date: Tue, 08 Apr 2025 21:37:39 GMT
Via: 1.1 varnish
X-Served-By: cache-bom4723-BOM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1744148259.774030,VS0,VE391
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: e6c16e84068913dcfb5289974bb7cb3e2ad33d71
Expires: Tue, 08 Apr 2025 21:42:39 GMT
Source-Age: 0

]
[2025-04-09 03:07:39,513: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<<<< 

x==========x]
[2025-04-09 03:39:02,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 03:39:03,214: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-09 03:39:03,237: INFO: common: created directory at: artifacts]
[2025-04-09 03:39:47,568: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 03:39:47,572: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-09 03:39:47,572: INFO: common: created directory at: artifacts]
[2025-04-09 03:39:47,572: INFO: common: created directory at: artifacts/data_validation]
[2025-04-09 03:41:04,879: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 03:41:04,881: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-09 03:41:04,881: INFO: common: created directory at: artifacts]
[2025-04-09 03:41:04,881: INFO: common: created directory at: artifacts/data_validation]
[2025-04-09 03:41:35,970: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 03:41:35,974: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-09 03:41:35,976: INFO: common: created directory at: artifacts]
[2025-04-09 03:41:35,979: INFO: common: created directory at: artifacts/data_validation]
[2025-04-09 03:41:52,699: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 03:41:52,700: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-09 03:41:52,704: INFO: common: created directory at: artifacts]
[2025-04-09 03:41:52,704: INFO: common: created directory at: artifacts/data_validation]
[2025-04-09 03:42:11,284: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 03:42:11,286: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-09 03:42:11,286: INFO: common: created directory at: artifacts]
[2025-04-09 03:42:11,286: INFO: common: created directory at: artifacts/data_validation]
[2025-04-09 04:01:28,870: INFO: main: >>>>> stage Data Validation Stage started <<<<<<<< 

x==========x]
[2025-04-09 04:01:28,870: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 04:01:28,870: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-09 04:01:28,870: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\src\datascience\utils\common.py", line 31, in read_yaml
    return ConfigBox(content)
  File "box\\box.py", line 295, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\main.py", line 12, in <module>
    obj.initiate_data_validation()
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\src\datascience\pipeline\data_validation_pipleine.py", line 15, in initiate_data_validation
    config=ValidationConfigurationManager()
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\src\datascience\config\configuration.py", line 34, in __init__
    self.params = read_yaml(params_filepath)
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\dsenv\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\src\datascience\utils\common.py", line 33, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2025-04-09 04:02:30,569: INFO: main: >>>>> stage Data Validation Stage started <<<<<<<< 

x==========x]
[2025-04-09 04:02:30,576: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 04:02:30,576: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-09 04:02:30,576: INFO: common: created directory at: artifacts]
[2025-04-09 04:02:30,576: INFO: common: created directory at: artifacts/data_validation]
[2025-04-09 04:02:30,580: ERROR: main: 'DataValiadtion' object has no attribute 'validaion_all_column']
Traceback (most recent call last):
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\main.py", line 12, in <module>
    obj.initiate_data_validation()
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\src\datascience\pipeline\data_validation_pipleine.py", line 18, in initiate_data_validation
    data_validation.validaion_all_column()
AttributeError: 'DataValiadtion' object has no attribute 'validaion_all_column'
[2025-04-09 04:04:00,507: INFO: main: >>>>> stage Data Validation Stage started <<<<<<<< 

x==========x]
[2025-04-09 04:04:00,508: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 04:04:00,508: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-09 04:04:00,512: INFO: common: created directory at: artifacts]
[2025-04-09 04:04:00,513: INFO: common: created directory at: artifacts/data_validation]
[2025-04-09 04:04:00,513: ERROR: main: name 'pd' is not defined]
Traceback (most recent call last):
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\main.py", line 12, in <module>
    obj.initiate_data_validation()
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\src\datascience\pipeline\data_validation_pipleine.py", line 18, in initiate_data_validation
    data_validation.validate_all_columns()
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\src\datascience\components\data_validation.py", line 33, in validate_all_columns
    raise e
  File "E:\Udemy\DataScienceProject_new\dsproject_1_new\src\datascience\components\data_validation.py", line 14, in validate_all_columns
    data = pd.read_csv(self.config.unzip_data_dir)
NameError: name 'pd' is not defined
[2025-04-09 04:05:02,210: INFO: main: >>>>> stage Data Validation Stage started <<<<<<<< 

x==========x]
[2025-04-09 04:05:02,210: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-09 04:05:02,210: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-04-09 04:05:02,210: INFO: common: created directory at: artifacts]
[2025-04-09 04:05:02,210: INFO: common: created directory at: artifacts/data_validation]
[2025-04-09 04:05:02,228: INFO: main: >>>>> stage Data Validation Stage completed <<<<<<<< 

x==========x]
[2025-04-11 00:44:32,230: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 00:44:32,635: INFO: common: yaml file: params.yaml loaded successfully]
[2025-04-11 00:46:25,623: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 00:46:25,974: INFO: common: created directory at: artifacts]
[2025-04-11 00:46:25,979: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-11 00:46:26,231: INFO: 4045112721: Splitted the data into training and test sets]
[2025-04-11 00:46:26,232: INFO: 4045112721: (1199, 12)]
[2025-04-11 00:46:26,233: INFO: 4045112721: (400, 12)]
[2025-04-11 01:02:14,882: INFO: main: >>>>> stage Data Validation Stage started <<<<<<<< 

x==========x]
[2025-04-11 01:02:14,884: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-04-11 01:02:14,885: INFO: common: created directory at: artifacts]
[2025-04-11 01:02:14,885: INFO: common: created directory at: artifacts/data_transformation]
[2025-04-11 01:02:14,929: INFO: data_transformation: Splitted the data into training and test sets]
[2025-04-11 01:02:14,929: INFO: data_transformation: (1199, 12)]
[2025-04-11 01:02:14,930: INFO: data_transformation: (400, 12)]
[2025-04-11 01:02:14,930: INFO: main: >>>>> stage Data Validation Stage completed <<<<<<<< 

x==========x]
